import NavbarDashboard from "../components/layout/navigation/Navbar.dashboard"
import { Poppins } from 'next/font/google'
import Sidebar from "../components/layout/navigation/Sidebar.dasboard"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ["100", '200', '300', '400', '500', '600', '700', '800']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} h-screen overflow-hidden bg-[#F8F8F8]`}>
        <NavbarDashboard />
        <div className="py-16 flex">
          <Sidebar />
          <div className="w-full h-full overflow-y-scroll p-8">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
